-- Minh hoa cach fix 1 cho MultipleBagFetchException: doi CA HAI collection tu
-- List sang Set (khong ben nao con la bag), de JOIN FETCH dong thoi ca hai
-- vua khong nem ngoai le vua khong bi nhan doi phan tu do cartesian product.
CREATE TABLE bagfetch_fix_parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE bagfetch_fix_items_a (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES bagfetch_fix_parents (id)
);

CREATE TABLE bagfetch_fix_items_b (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES bagfetch_fix_parents (id)
);
