-- Bang RIENG cho fix optimistic locking (muc 18) - tach khoi "inventory" de
-- khong anh huong ban naive o muc 17 (xem ghi chu trong Inventory.java).
CREATE TABLE optimistic_inventory (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity_on_hand  INTEGER NOT NULL,
    version           BIGINT  NOT NULL DEFAULT 0
);
