-- Bang cho 4 bay @Transactional (muc 20).
CREATE TABLE tx_demo_records (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label  VARCHAR(255) NOT NULL
);

CREATE TABLE tx_demo_audit_logs (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message  VARCHAR(255) NOT NULL
);
