CREATE TABLE orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    status        VARCHAR(50)  NOT NULL
);

-- order_id de NULL duoc (khong NOT NULL) de co the tai hien bug FK bi null o muc 2
-- cua lo trinh. Trong schema production that, cot nay nen la NOT NULL de DB tu
-- chan bug nay bang mot loi rang buoc thay vi luu sai du lieu trong im lang.
CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_sku  VARCHAR(100) NOT NULL,
    quantity     INTEGER      NOT NULL,
    order_id     BIGINT REFERENCES orders (id)
);
