-- Bang phuc vu rieng cho bai hoc "Cascade va orphanRemoval". Moi cap bang la
-- mot cau hinh cascade khac nhau tren CUNG mot quan he Order/OrderItem, de co
-- the so sanh hanh vi canh nhau ma khong anh huong den bang orders/order_items
-- (bang "that" cua bai truoc, dang la cau hinh CascadeType.ALL + orphanRemoval=true).

-- Kich ban 1: KHONG cascade, KHONG orphanRemoval
CREATE TABLE no_cascade_orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL
);

CREATE TABLE no_cascade_order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_sku VARCHAR(100) NOT NULL,
    order_id    BIGINT       NOT NULL REFERENCES no_cascade_orders (id)
);

-- Kich ban 2: chi CascadeType.REMOVE (khong orphanRemoval)
CREATE TABLE cascade_remove_orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL
);

CREATE TABLE cascade_remove_order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_sku VARCHAR(100) NOT NULL,
    order_id    BIGINT       NOT NULL REFERENCES cascade_remove_orders (id)
);

-- Kich ban 3: chi orphanRemoval = true (cascade chi co PERSIST, khong co REMOVE)
CREATE TABLE orphan_removal_orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL
);

CREATE TABLE orphan_removal_order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_sku VARCHAR(100) NOT NULL,
    order_id    BIGINT       NOT NULL REFERENCES orphan_removal_orders (id)
);

-- Anti-pattern co chu dich: OrderItem -> Product voi cascade = ALL. Product la
-- danh muc dung chung, khong phai thu "song chet theo" mot don hang cu the.
CREATE TABLE bad_cascade_orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL
);

CREATE TABLE bad_cascade_order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL REFERENCES bad_cascade_orders (id),
    product_id  BIGINT NOT NULL REFERENCES products (id)
);
