-- Bang phuc vu bai hoc "equals/hashCode cho entity". Moi bang tuong ung mot
-- chien luoc equals/hashCode khac nhau tren cung mot hinh dang du lieu
-- (product_sku, quantity) de so sanh hanh vi trong HashSet.

CREATE TABLE id_equality_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_sku VARCHAR(100) NOT NULL,
    quantity    INTEGER      NOT NULL
);

CREATE TABLE all_fields_equality_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_sku VARCHAR(100) NOT NULL,
    quantity    INTEGER      NOT NULL
);

CREATE TABLE business_key_equality_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_key VARCHAR(36)  NOT NULL UNIQUE,
    product_sku  VARCHAR(100) NOT NULL,
    quantity     INTEGER      NOT NULL
);
