-- OWNING side cua quan he 1-1 voi Product: FK + UNIQUE de bao dam that su la
-- 1-1 (moi product co nhieu nhat mot dong inventory).
CREATE TABLE inventory (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT  NOT NULL UNIQUE REFERENCES products (id),
    quantity_on_hand  INTEGER NOT NULL
);
