-- Kich ban A: @ManyToMany voi List (bag semantics)
CREATE TABLE bag_demo_products (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE bag_demo_tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE bag_demo_product_tags (
    product_id BIGINT NOT NULL REFERENCES bag_demo_products (id),
    tag_id     BIGINT NOT NULL REFERENCES bag_demo_tags (id),
    PRIMARY KEY (product_id, tag_id)
);

-- Kich ban B: @ManyToMany voi Set
CREATE TABLE set_demo_products (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE set_demo_tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE set_demo_product_tags (
    product_id BIGINT NOT NULL REFERENCES set_demo_products (id),
    tag_id     BIGINT NOT NULL REFERENCES set_demo_tags (id),
    PRIMARY KEY (product_id, tag_id)
);

-- Kich ban C (production): tach ManyToMany thanh join entity tuong minh de
-- moi dong co dinh danh (id) rieng, khong con la mot "bag" vo danh nua, va co
-- the mang them metadata (created_at, sort_order).
CREATE TABLE tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE product_tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT      NOT NULL REFERENCES products (id),
    tag_id     BIGINT      NOT NULL REFERENCES tags (id),
    created_at TIMESTAMP   NOT NULL,
    sort_order INTEGER     NOT NULL,
    UNIQUE (product_id, tag_id)
);
