-- Adjacency list: moi row tu tro ve parent cua no qua parent_id (NULL = root).
CREATE TABLE categories (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    parent_id BIGINT REFERENCES categories (id)
);
