-- @BatchSize khong the gan tren Order/OrderItem that (se pha assertion 101
-- query cua muc 8), nen dung cap bang rieng cho tung ky thuat con lai.
CREATE TABLE batch_size_orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL
);

CREATE TABLE batch_size_order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_sku VARCHAR(100) NOT NULL,
    order_id    BIGINT       NOT NULL REFERENCES batch_size_orders (id)
);

CREATE TABLE subselect_orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL
);

CREATE TABLE subselect_order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_sku VARCHAR(100) NOT NULL,
    order_id    BIGINT       NOT NULL REFERENCES subselect_orders (id)
);
