CREATE TABLE order_status_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT      NOT NULL REFERENCES orders (id),
    status     VARCHAR(50) NOT NULL,
    changed_at TIMESTAMP   NOT NULL
);
